name: myapp
description: A simple command-line application using Realm Dart SDK.

publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  realm_dart_vector_db:
    path: ../

dev_dependencies:
  lints: ^5.1.1
